# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Treborctl < Formula
  desc "Treborctl command line tool"
  homepage "https://github.com/trebornaut/releases"
  version "0.3.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://raw.githubusercontent.com/trebornaut/releases/main/treborctl/treborctl_Darwin_x86_64.zip"
      sha256 "f37d2267ea4bddae0e165113b929783a6a9eeb1b227ba3c8d793be808ad99957"

      def install
        bin.install "treborctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://raw.githubusercontent.com/trebornaut/releases/main/treborctl/treborctl_Darwin_arm64.zip"
      sha256 "8cc7f55337f83a83e5b4cf5276c33de97eed61ce3d5cfd30475f28dc260e239a"

      def install
        bin.install "treborctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://raw.githubusercontent.com/trebornaut/releases/main/treborctl/treborctl_Linux_x86_64.zip"
      sha256 "58ebc3016fda79bbe372682acf3094020dc6d3b8ff33aa40b76ae873c32271f7"
      def install
        bin.install "treborctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://raw.githubusercontent.com/trebornaut/releases/main/treborctl/treborctl_Linux_arm64.zip"
      sha256 "09ddcb835cd50df2d9ffdf000c95821c303432362e24525415a29aa161bf0be6"
      def install
        bin.install "treborctl"
      end
    end
  end

  test do
    system "#{bin}/treborctl", "--version"
  end
end
